language: ruby
dist: xenial
rvm:
  - 2.4.4

before_install:
  - sudo apt-get install ruby-rmagick libfreeimage3 libfreeimage-dev zip nodejs gdal-bin imagemagick python-gdal
  
install:
  - bundle install

script:
  - ruby test/exporter_test.rb
