sudo: required
services:
  - docker
#language: ruby
#rvm:
#  - 2.4.4

install:
    docker build . -t lib-mapknitter-exporter:latest

script:
    docker run lib-mapknitter-exporter ruby test/exporter_test.rb
